### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/amd-ryzen#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'Unwatch' button and selecting either the 'Not watching' or 'Ignoring' option.

**Comment by stoe** [comment]
👋  y'all and welcome to our training class
🐙🐱💖

**Comment by beardofedu** [comment]
hello 👋 

## headings

- bullet
- bullet2

1. one 
1. two
1. three

**Comment by badstreff** [comment]
1st

**Comment by susanliu2020** [comment]
Hello, this is Susan, I want to learn Github

**Comment by susanliu2020** [comment]
Thank you

**Comment by jared-sanders** [comment]
`Hello`

**Comment by MaxRBosch** [comment]
Hi!

**Comment by KlaasAbma** [comment]
Hello

**Comment by nsoniat** [comment]
i love my new GitHub account!!! ❤️

**Comment by jiny-joseph** [comment]
Hi 👍

**Comment by rgondesi** [comment]
Awesome!!

**Comment by shrutim97** [comment]
helloooooo

**Comment by Qingbin-PAN** [comment]
Hi

**Comment by DevGuangLi** [comment]
hi

**Comment by tmahesh1975** [comment]
I see it now :)
